version: '3'

services:
  python:
    image: python
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
#    command: flask run --host 0.0.0.0 --port 5000