version: '3'

services:
  python:
    image: python
    build: .
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - "./:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
#    command: flask run --host 0.0.0.0 --port 5000

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./src/db/data:/var/lib/mysql
      - ./src/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./src/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8080:8080